title: "Reading Polyamory & ENM Discussion Group"
description: "A community for discussing ethical non-monogamy."

collections:
  sections:
    output: false

defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      order: 999

exclude:
  - docs
  - test
  - Gemfile
  - Gemfile.lock
  - README.md

